system:
  ip: 127.0.0.1
  port: 8080
  env: dev
  gin_mode: debug
db:
  - user: root
    password: root
    host: 127.0.0.1
    port: 3306
    db: tpc_h
    debug: false
    source: mysql
    max_conn: 100
    max_idle: 10
    max_lifetime: 3
jwt:
  expire: 3000
  secret: TOKYO-ANON
  issuer: amamiya